language: java
install: true
jdk:
  - openjdk11
env:
  global:
    - secure:
    - secure: EMJQSP/DStAuVYFP7mxIXT67Ze07JzTHq1Lg5MbKXHM4b3vXEKyw3sPN1BC+LjTqoV9LpdtopjJKUzN7fHHFBXt3wnBIZ9rErb9tI1gJHSRaIyoh0xuhWPgIc071VdkZKFL7Qz/6j5dfPuWclb7Gi9wA+RnSxRi1Cgf9Ujyky8LKA1nSZsjaHZfcQJ5LWx6q8nPSp8I0hIJ/EnPXUpnx3qXCOOQRbgS25bPdSY/tNOR3/MUn6JuY32E8lABt1Tc2StIJfs08Onu5LprMP7tuCw8scCk/u2ugNvJhsUpuioSqB5fhrVg07CjAFrbUV4Sx7ubEu9aUPp1NEJbZqGkjLKez8T2wGNS4PRwgH1fKnF19v40vglOUmoq2iUqBX/+0L8i4spmV6ihEfoe+zu4SXB8iFO2gxf666WkrOcTDTen+Df+xWQGPB4P1lAbvEPhL7ajLzE42sPtMlyRm1RcfDgb6rQ0gxdcaarPKjzTVr8Y3v9j4B1aPW/ZBJoeJtdMeNQUojuGjKOpKjSZKDEuaJanuPfx5Dx95FMb/efhZbebRtoT7VVd/N1empSYjYNK5E6lkftj5ozGyrJn9P/xv7XgYYwaA9Btg1NShQUecbeQQBbT5HS21qHqq+AiiIRTtlYN4SWivCtb8WBrjreB3oiGzyXWVrufbQIhIIpP0gK0=
addons:
  host:
    - mysql-server
  sonarcloud:
    organization: sunxuia
    token:
      secure: IWHL4C0KCrOMkyaGMJzJATxE8l0Gv/Wr0tIQfQx7iGcr3Dh5B9xh9v8H2UuaM/0AiC/NBzV32EfF5AGr8joHXPGcwOnV/9pM6qQwqDM0Ex0EYELqikV26H/ZURsum2W4jqQY5jWrIR6NCoCDVAaq0fRVIRb7UFwiRFbA5khkRAzcGhS7hPppbh1sA0i7EteUMtnygUawkh/Qw+HX8PZ0r3BATh3+kuipn/S1wcllOibbtBoOyHGeDCgW9K1B+SiogYgG0i8PAQJ+/TKcppDAMtD7RnQe6pj13m91C+MoQxms0putPsgkXm9UhGRCZ6a1YcvqyPu5KXy2WM0N3GLGudnHeKX4RVZmlyYZZZR1Jzrp/iwcvKPCqJq2RoZi5gafHe7AUp/g2pDMA7/YMZpvNRk8KSsgWmNIO07Cc+V+t72dymG3CHYpc49vcleFHk54xwIMuaq1k7aOaszmEqEYwR5cHiPae8SpjcLaH+7cRhmKxy343ahEnXpBtaYAURRQXb3U/+HnHA7A2ajgeXLlzYgyuP258bneoYf+3RMqUW3rwEzrKobJaIVdQpAMHNi97qRv4vVLiWFISECeeKny5FN9uO3LYrx8TAZRJF0xGqcG2peTegX+VpuB1mViwWoJeS+8tER1CV7nv6d5J/H3apyPEN/wFE/6WMB7mwzteOI=
before_script:
  - wget https://dev.mysql.com/get/mysql-apt-config_0.8.13-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.13-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew
    mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - echo 'mysql version is ' `mysql --version`
  - mysql -u root -e 'CREATE DATABASE tstdb;'
  - mysql -u root -e "CREATE USER 'tstuser'@'localhost' IDENTIFIED BY '123456';"
  - mysql -u root -e "GRANT ALL ON tstdb.* TO 'tstuser'@'localhost';"
script: chmod +x build.sh && ./build.sh
